image:
  name: sabatmonk/doctoolchain-docker
  entrypoint: ["/bin/sh", "-c"]

html:
  script:
    - doctoolchain .training_guide/english generateHTML
  artifacts:
    paths:
      - "html5/*"

pdf:
  script:
    - .training_guide/english generatePDF
  artifacts:
    paths:
      - "*.pdf"
