image:
  name: sabatmonk/doctoolchain-docker
  entrypoint: ["/bin/sh", "-c"]

html:
  script:
    - doctoolchain ./training_guide/english generateHTML
  artifacts:
    paths:
      - "./training_guide/english/build/html5/*"
pdf:
  script:
    - doctoolchain ./training_guide/english generatePDF
  artifacts:
    paths:
      - "./training_guide/english/build/pdf/*"
