image:
  name: sabatmonk/doctoolchain-docker
  entrypoint: ["/bin/sh", "-c"]

html:
  script:
    - ls -la
    - doctoolchain .training_guide/english generateHTML
  artifacts:
    paths:
      - "html5/*"
